# These are supported funding model platforms

#github: [solemcaelum] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: carameldrop # Replace with a single Patreon username
ko_fi: carameldrop # Replace with a single Ko-fi username
